server:
  port: 8003
spring:
  application:
    name: provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: localhost:2181
mybatis:
  mapper-locations: classpath*:mapper/*:xml
  type-aliases-package: org.hui.payment.entity

