server:
  port: 8210
spring:
  application:
    name: consumer-order-feign-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# 设置feign客户端的超时时间
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimout: 5000\

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    org.hui.service.PaymentFeignHystrixService: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
